version: 0.2

phases:
  install:
    commands:
      - echo Upgrading packages
      - apt-get update -y && apt-get upgrade -y
      # install Node LTS
      - echo installing Node
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo installing packages
      - npm i 
      # - echo Testing
      # - npm run test
  build:
    commands: 
      - echo Building Project started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build is completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build